safe:        true
markdown: kramdown
exclude: [node_modules, bower_components, vendor]
baseurl: /cn
url: https://www.jhipster.tech/cn
github_repository_url: https://github.com/jhipster/cn
kramdown:
  input: GFM
gems:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
defaults:
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
